owner: rescuetablet # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Homepage
    url: https://rescuetablet.de
  - name: App
    url: https://app.rescuetablet.com
  - name: App API
    url: https://app-api.rescuetablet.com/
  - name: Missions API
    url: https://missions-api.rescuetablet.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.rescuetablet.com
  # baseUrl: /status
  logoUrl: https://app.rescuetablet.com/logo.svg
  name: rescueTABLET Status
  introTitle: "This is the **rescueTABLET** status page, where you can check whether all of our systems are running smoothly."
  introMessage: If you need support, please contact our support at [info@rescuetablet.de](mailto:info@rescuetablet.de) or [+49 (0)6058 5399996](tel:+4960585399996) (also via WhatsApp).
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
